# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.slot_machine.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:slot_machine/as_root/pre_tick
execute if entity @s[tag=aj.slot_machine.animation.pull_lever.playing] run function animated_java:slot_machine/animations/pull_lever/zzz/on_tick
execute if entity @s[tag=aj.slot_machine.animation.spin_start.playing] run function animated_java:slot_machine/animations/spin_start/zzz/on_tick
execute if entity @s[tag=aj.slot_machine.animation.spin_loop1.playing] run function animated_java:slot_machine/animations/spin_loop1/zzz/on_tick
execute if entity @s[tag=aj.slot_machine.animation.spin_loop2.playing] run function animated_java:slot_machine/animations/spin_loop2/zzz/on_tick
execute if entity @s[tag=aj.slot_machine.animation.spin_loop3.playing] run function animated_java:slot_machine/animations/spin_loop3/zzz/on_tick
execute if entity @s[tag=aj.slot_machine.animation.stop_lose1.playing] run function animated_java:slot_machine/animations/stop_lose1/zzz/on_tick
execute if entity @s[tag=aj.slot_machine.animation.stop_lose2.playing] run function animated_java:slot_machine/animations/stop_lose2/zzz/on_tick
execute if entity @s[tag=aj.slot_machine.animation.stop_lose3.playing] run function animated_java:slot_machine/animations/stop_lose3/zzz/on_tick
execute if entity @s[tag=aj.slot_machine.animation.stop_lose4.playing] run function animated_java:slot_machine/animations/stop_lose4/zzz/on_tick
execute if entity @s[tag=aj.slot_machine.animation.stop_lose5.playing] run function animated_java:slot_machine/animations/stop_lose5/zzz/on_tick
execute if entity @s[tag=aj.slot_machine.animation.stop_lose6.playing] run function animated_java:slot_machine/animations/stop_lose6/zzz/on_tick
execute if entity @s[tag=aj.slot_machine.animation.stop_lose7.playing] run function animated_java:slot_machine/animations/stop_lose7/zzz/on_tick
execute if entity @s[tag=aj.slot_machine.animation.win1.playing] run function animated_java:slot_machine/animations/win1/zzz/on_tick
execute if entity @s[tag=aj.slot_machine.animation.win2.playing] run function animated_java:slot_machine/animations/win2/zzz/on_tick
execute if entity @s[tag=aj.slot_machine.animation.win3.playing] run function animated_java:slot_machine/animations/win3/zzz/on_tick
execute if entity @s[tag=aj.slot_machine.animation.win4.playing] run function animated_java:slot_machine/animations/win4/zzz/on_tick
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:slot_machine/as_root/post_tick