# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.slot_machine.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'slot_machine', 'function_path': 'animated_java:slot_machine/animations/pull_lever/set_frame'}
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.pull_lever.frame $(frame)
execute at @s run function animated_java:slot_machine/animations/pull_lever/zzz/set_frame with storage aj:temp