# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:slot_machine/animations/spin_loop1/zzz/apply_frame {frame: 60}
scoreboard players add @s aj.spin_loop1.frame 1