# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.slot_machine.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'slot_machine', 'function_path': 'animated_java:slot_machine/variants/default/apply'}
execute on passengers if entity @s[tag=aj.slot_machine.bone.handle2] run function animated_java:slot_machine/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.slot_machine.bone.wheel2] run function animated_java:slot_machine/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.slot_machine.bone.wheel3] run function animated_java:slot_machine/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.slot_machine.bone.wheel4] run function animated_java:slot_machine/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.slot_machine.bone.main2] run function animated_java:slot_machine/variants/default/zzz/4