# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.slot_machine.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'slot_machine', 'function_path': 'animated_java:slot_machine/animations/stop_lose1/next_frame'}
execute if score @s aj.stop_lose1.frame matches 21.. run scoreboard players set @s aj.stop_lose1.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.stop_lose1.frame
execute at @s run function animated_java:slot_machine/animations/stop_lose1/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.stop_lose1.frame 1