# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.slot_machine.bone.handle2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_handle2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.slot_machine.bone.wheel2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheel2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.slot_machine.bone.wheel3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheel3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.slot_machine.bone.wheel4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheel4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.slot_machine.bone.main2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_main2 set from storage aj:uuid main.out