# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.slot_machine.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'slot_machine', 'function_path': 'animated_java:slot_machine/animations/pause_all'}
tag @s remove aj.slot_machine.animation.pull_lever.playing
tag @s remove aj.slot_machine.animation.spin_start.playing
tag @s remove aj.slot_machine.animation.spin_loop1.playing
tag @s remove aj.slot_machine.animation.spin_loop2.playing
tag @s remove aj.slot_machine.animation.spin_loop3.playing
tag @s remove aj.slot_machine.animation.stop_lose1.playing
tag @s remove aj.slot_machine.animation.stop_lose2.playing
tag @s remove aj.slot_machine.animation.stop_lose3.playing
tag @s remove aj.slot_machine.animation.stop_lose4.playing
tag @s remove aj.slot_machine.animation.stop_lose5.playing
tag @s remove aj.slot_machine.animation.stop_lose6.playing
tag @s remove aj.slot_machine.animation.stop_lose7.playing
tag @s remove aj.slot_machine.animation.win1.playing
tag @s remove aj.slot_machine.animation.win2.playing
tag @s remove aj.slot_machine.animation.win3.playing
tag @s remove aj.slot_machine.animation.win4.playing