# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:slot_machine/animations/spin_loop3/zzz/apply_frame {frame: 55}
scoreboard players add @s aj.spin_loop3.frame 1