# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:slot_machine/animations/spin_loop2/zzz/apply_frame {frame: 50}
scoreboard players add @s aj.spin_loop2.frame 1