# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.slot_machine.root] run return 0
execute on passengers if entity @s[tag=aj.slot_machine.data] unless data entity @s {data:{rigHash: '70e427e1609491d4d3e0dd81253d50030bec7f59852fd4f734da496f44868cdc'}} on vehicle run function animated_java:slot_machine/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1