# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.pull_lever.frame dummy
scoreboard objectives add aj.spin_start.frame dummy
scoreboard objectives add aj.spin_loop1.frame dummy
scoreboard objectives add aj.spin_loop2.frame dummy
scoreboard objectives add aj.spin_loop3.frame dummy
scoreboard objectives add aj.stop_lose1.frame dummy
scoreboard objectives add aj.stop_lose2.frame dummy
scoreboard objectives add aj.stop_lose3.frame dummy
scoreboard objectives add aj.stop_lose4.frame dummy
scoreboard objectives add aj.stop_lose5.frame dummy
scoreboard objectives add aj.stop_lose6.frame dummy
scoreboard objectives add aj.stop_lose7.frame dummy
scoreboard objectives add aj.win1.frame dummy
scoreboard objectives add aj.win2.frame dummy
scoreboard objectives add aj.win3.frame dummy
scoreboard objectives add aj.win4.frame dummy