# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.slot_machine.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'slot_machine', 'function_path': 'animated_java:slot_machine/animations/spin_start/stop'}
tag @s remove aj.slot_machine.animation.spin_start.playing
scoreboard players set @s aj.spin_start.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:slot_machine/animations/spin_start/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only